### ISSUE TITLE
Raises :unsupport_option error with {:system, "ENV_NAME"} in config

### ISSUE THREAD

**Issue by asakura** [OvermindDL1/pid_file#1]
`** (EXIT) bad return value: {:unsupport_option, PidFile.Worker, :init, :file, '/home/deploy/froodi/froodi.pid', [file: '/home/deploy/froodi/froodi.pid']}
`
Probably that case expression https://github.com/OvermindDL1/pid_file/blob/master/lib/pid_file/worker.ex#L16 must take into account Erlang strings too.

**Comment by OvermindDL1** [comment]
I thought about doing that originally but I use binaries myself and a list might be useful for some other format later (encoding path via entry for example), though I guess such usages could always be wrapped up in 2-tuples or new options anyway.

For now you can use a binary, I'll have the next version (out probably today) add support for iolists.  :-)

**Comment by OvermindDL1** [comment]
Version 0.1.1 is out with that feature added.  :-)

**Comment by asakura** [comment]
Thanks! I'll try it.
